/* KidGenius Club - Bono #3: Calendario de Aventuras
   Base de Datos de 30 Misiones Diarias KidGenius */

const MISSIONS_DATA = [
  // ================= SEMANA 1: EXPLORADORES DE NÚMEROS =================
  {
    day: 1,
    week: 1,
    title: "El Nido del T-Rex",
    icon: "🥚",
    story: "¡Hola! Soy Geni. Encontramos 4 huevos de dinosaurio dorados y luego 3 huevos verdes. ¿Cuántos huevos tenemos en total?",
    type: "options",
    question: "4 + 3 = ?",
    visuals: ["🥚", "🥚", "🥚", "🥚", "➕", "🟢", "🟢", "🟢"],
    options: ["6", "7", "8", "9"],
    correct: "7",
    hint: "Cuenta los 4 huevos dorados y sigue sumando: 5, 6, 7.",
    reward: { sticker: "🦕", name: "Sticker Cría de Rex" }
  },
  {
    day: 2,
    week: 1,
    title: "Huellas en la Cueva",
    icon: "🐾",
    story: "El velociraptor dejó huellas en saltos de 2 en 2. ¿Qué número falta en el camino?",
    type: "options",
    question: "2, 4, 6, ❓, 10",
    visuals: ["🐾", "🐾", "🐾", "❓", "🐾"],
    options: ["7", "8", "9", "12"],
    correct: "8",
    hint: "Suma 2 al número 6: 6 + 2 = ...",
    reward: { sticker: "🐾", name: "Huella Prehistórica" }
  },
  {
    day: 3,
    week: 1,
    title: "Frutas del Triceratops",
    icon: "🍎",
    story: "Trixie tenía 9 manzanas mágicas y compartió 4 con su amigo Bronto. ¿Cuántas le quedan?",
    type: "options",
    question: "9 - 4 = ?",
    visuals: ["🍎", "🍎", "🍎", "🍎", "🍎", "🍎", "🍎", "🍎", "🍎"],
    options: ["3", "4", "5", "6"],
    correct: "5",
    hint: "Empieza en 9 y retrocede 4 números.",
    reward: { sticker: "🍏", name: "Manzana Gigante" }
  },
  {
    day: 4,
    week: 1,
    title: "El Árbol Más Alto",
    icon: "🌴",
    story: "Compara estas dos alturas de fósiles: ¿Cuál es el número MAYOR?",
    type: "options",
    question: "¿Cuál es mayor: 38 o 83?",
    visuals: ["🦴 38", "⚡", "🦴 83"],
    options: ["38", "83", "Son iguales", "Ninguno"],
    correct: "83",
    hint: "Mira la primera cifra: el 8 en las decenas vale 80.",
    reward: { sticker: "🌲", name: "Árbol Milenario" }
  },
  {
    day: 5,
    week: 1,
    title: "Rocas Dobles",
    icon: "🪨",
    story: "¡Desafío de dobles! Si una roca tiene 6 cristales brillantes, ¿cuántos cristales tendrán 2 rocas idénticas?",
    type: "options",
    question: "El doble de 6 (6 + 6) = ?",
    visuals: ["💎💎💎💎💎💎", "➕", "💎💎💎💎💎💎"],
    options: ["10", "11", "12", "14"],
    correct: "12",
    hint: "6 + 6 es igual a una docena.",
    reward: { sticker: "💎", name: "Gema Prehistórica" }
  },
  {
    day: 6,
    week: 1,
    title: "El Puente Colgante",
    icon: "🌉",
    story: "Para cruzar el puente necesitamos completar 10 tablones. Ya tenemos 7. ¿Cuántos nos faltan?",
    type: "options",
    question: "7 + ❓ = 10",
    visuals: ["🪵", "🪵", "🪵", "🪵", "🪵", "🪵", "🪵", "❓", "❓", "❓"],
    options: ["2", "3", "4", "5"],
    correct: "3",
    hint: "¿Cuánto le falta a 7 para llegar a la decena mágica 10?",
    reward: { sticker: "🪵", name: "Tablón de Oro" }
  },
  {
    day: 7,
    week: 1,
    title: "Gran Fiesta del Valle",
    icon: "🎉",
    story: "¡Fin de la Semana 1! 5 pterodáctilos en el cielo se juntan con 8 más. ¿Cuántos vuelan juntos?",
    type: "options",
    question: "5 + 8 = ?",
    visuals: ["🦅🦅🦅🦅🦅", "➕", "🦅🦅🦅🦅🦅🦅🦅🦅"],
    options: ["12", "13", "14", "15"],
    correct: "13",
    hint: "Puedes sumar 5 + 5 = 10 y luego agregar 3 más.",
    reward: { sticker: "👑", name: "Corona de la Selva" }
  },

  // ================= SEMANA 2: MAESTROS DEL CÁLCULO RÁPIDO =================
  {
    day: 8,
    week: 2,
    title: "Velocidad de Volcán",
    icon: "🌋",
    story: "¡El volcán está activo! Resuelve esta suma relámpago con decenas completas:",
    type: "options",
    question: "20 + 30 = ?",
    visuals: ["🔥 2 decenas", "➕", "🔥 3 decenas"],
    options: ["40", "50", "60", "70"],
    correct: "50",
    hint: "Suma 2 + 3 y agrégale el cero al final.",
    reward: { sticker: "🌋", name: "Lava Rubí" }
  },
  {
    day: 9,
    week: 2,
    title: "La Cascada del Misterio",
    icon: "🌊",
    story: "Había 15 peces nadando en la cascada. 6 saltaron a otra laguna. ¿Cuántos quedaron?",
    type: "options",
    question: "15 - 6 = ?",
    visuals: ["🐟", "🐟", "🐟", "🐟", "🐟", "🐟", "🐟", "🐟", "🐟", "🐟", "🐟", "🐟", "🐟", "🐟", "🐟"],
    options: ["8", "9", "10", "11"],
    correct: "9",
    hint: "15 menos 5 es 10, y si quitas 1 más te da...",
    reward: { sticker: "🐟", name: "Pez de Cristal" }
  },
  {
    day: 10,
    week: 2,
    title: "El Cofre del Estegosaurio",
    icon: "🧰",
    story: "Para abrir el candado, encuentra el número que es 10 unidades MENOR que 45.",
    type: "options",
    question: "45 - 10 = ?",
    visuals: ["🔒", "45", "➖", "10"],
    options: ["30", "35", "40", "55"],
    correct: "35",
    hint: "Solo resta 1 a la cifra de las decenas (4 - 1 = 3).",
    reward: { sticker: "🔑", name: "Llave Fósil" }
  },
  {
    day: 11,
    week: 2,
    title: "Grupos de Helechos",
    icon: "🌿",
    story: "Tenemos 3 nidos y en cada nido hay 4 huevos. ¿Cuántos huevos hay en total?",
    type: "options",
    question: "3 x 4 (o 4 + 4 + 4) = ?",
    visuals: ["🥚🥚🥚🥚", "🥚🥚🥚🥚", "🥚🥚🥚🥚"],
    options: ["10", "11", "12", "14"],
    correct: "12",
    hint: "4 + 4 = 8, y 8 + 4 = ...",
    reward: { sticker: "🌿", name: "Helecho Gigante" }
  },
  {
    day: 12,
    week: 2,
    title: "Paso de Meteoritos",
    icon: "☄️",
    story: "¡Meteoritos en formación! ¿Qué número sigue en esta serie de 5 en 5?",
    type: "options",
    question: "5, 10, 15, 20, ❓",
    visuals: ["⭐ 5", "⭐ 10", "⭐ 15", "⭐ 20", "❓"],
    options: ["22", "25", "30", "35"],
    correct: "25",
    hint: "Suma 5 al número 20.",
    reward: { sticker: "☄️", name: "Cometa Mágico" }
  },
  {
    day: 13,
    week: 2,
    title: "Los Ojos de la Noche",
    icon: "🦉",
    story: "Contamos 8 búhos en una rama y cada búho tiene 2 ojos brillantes. ¿Cuántos ojos vemos?",
    type: "options",
    question: "8 x 2 = ?",
    visuals: ["👀", "👀", "👀", "👀", "👀", "👀", "👀", "👀"],
    options: ["14", "16", "18", "20"],
    correct: "16",
    hint: "Es el doble de 8 (8 + 8).",
    reward: { sticker: "👁️", name: "Visión Nocturna" }
  },
  {
    day: 14,
    week: 2,
    title: "Celebración de Mitad de Camino",
    icon: "🏆",
    story: "¡Completaste 2 semanas enteras! Resuelve este super reto: ¿Cuánto es 25 + 25?",
    type: "options",
    question: "25 + 25 = ?",
    visuals: ["🪙 25", "➕", "🪙 25"],
    options: ["40", "45", "50", "55"],
    correct: "50",
    hint: "20 + 20 = 40, y 5 + 5 = 10. 40 + 10 = ...",
    reward: { sticker: "🥈", name: "Medalla de Plata KidGenius" }
  },

  // ================= SEMANA 3: GUARDIANES DE LA GEOMETRÍA Y PATRONES =================
  {
    day: 15,
    week: 3,
    title: "El Escudo Triangular",
    icon: "📐",
    story: "Geni encontró un escudo mágico con forma de triángulo. ¿Cuántos lados tiene un triángulo?",
    type: "options",
    question: "¿Cuántos lados tiene un triángulo?",
    visuals: ["🔺"],
    options: ["2", "3", "4", "5"],
    correct: "3",
    hint: "Tri- significa tres.",
    reward: { sticker: "🔺", name: "Escudo TriForce" }
  },
  {
    day: 16,
    week: 3,
    title: "Pizza Prehistórica",
    icon: "🍕",
    story: "Dividimos una pizza de hojas gigantes en 4 partes iguales y nos comimos 2. ¿Qué fracción comimos?",
    type: "options",
    question: "2 partes de 4 es igual a...",
    visuals: ["🍕", "Dividida en 4 trozos", "Comidos: 2"],
    options: ["La mitad (1/2)", "Un tercio (1/3)", "Toda entera", "Un cuarto (1/4)"],
    correct: "La mitad (1/2)",
    hint: "2 es exactamente la mitad de 4.",
    reward: { sticker: "🍕", name: "Pizza Jurásica" }
  },
  {
    day: 17,
    week: 3,
    title: "El Reloj del Sol",
    icon: "☀️",
    story: "El sol marca el mediodía. Si son las 3:00 de la tarde y pasan 2 horas, ¿qué hora será?",
    type: "options",
    question: "3:00 + 2 horas = ?",
    visuals: ["🕒 3:00", "➕ 2 horas ➡️", "❓"],
    options: ["4:00", "5:00", "6:00", "7:00"],
    correct: "5:00",
    hint: "3 + 2 = 5.",
    reward: { sticker: "☀️", name: "Sol Radiante" }
  },
  {
    day: 18,
    week: 3,
    title: "Patrón de Estrellas",
    icon: "✨",
    story: "Descubre el patrón: Rojo, Azul, Rojo, Azul, Rojo... ¿Cuál sigue?",
    type: "options",
    question: "🔴, 🔵, 🔴, 🔵, 🔴, ❓",
    visuals: ["🔴", "🔵", "🔴", "🔵", "🔴", "❓"],
    options: ["🔴 Rojo", "🔵 Azul", "🟢 Verde", "🟡 Amarillo"],
    correct: "🔵 Azul",
    hint: "Los colores van alternándose uno a uno.",
    reward: { sticker: "✨", name: "Estrella Bicolor" }
  },
  {
    day: 19,
    week: 3,
    title: "El Castillo Cuadrado",
    icon: "🏰",
    story: "Una muralla cuadrada mide 5 metros en cada uno de sus 4 lados. ¿Cuánto mide todo el perímetro?",
    type: "options",
    question: "5 + 5 + 5 + 5 (o 4 x 5) = ?",
    visuals: ["⏹️ 5m", "⏹️ 5m", "⏹️ 5m", "⏹️ 5m"],
    options: ["15 m", "18 m", "20 m", "25 m"],
    correct: "20 m",
    hint: "Cuenta de 5 en 5 cuatro veces: 5, 10, 15, 20.",
    reward: { sticker: "🏰", name: "Fortaleza Dino" }
  },
  {
    day: 20,
    week: 3,
    title: "Cálculo de Monedas de Oro",
    icon: "💰",
    story: "Tienes 3 monedas de 10 puntos y 4 monedas de 1 punto. ¿Cuántos puntos tienes en total?",
    type: "options",
    question: "30 + 4 = ?",
    visuals: ["🪙10", "🪙10", "🪙10", "➕", "🪙1", "🪙1", "🪙1", "🪙1"],
    options: ["34", "43", "304", "7"],
    correct: "34",
    hint: "3 decenas (30) más 4 unidades (4).",
    reward: { sticker: "💰", name: "Bolsa de Oro" }
  },
  {
    day: 21,
    week: 3,
    title: "El Laberinto de las 3 Semanas",
    icon: "🌀",
    story: "¡3 semanas superadas con éxito! ¿Cuánto es 100 menos 20?",
    type: "options",
    question: "100 - 20 = ?",
    visuals: ["💯", "➖", "20"],
    options: ["70", "80", "90", "85"],
    correct: "80",
    hint: "A 10 decenas le quitas 2 decenas.",
    reward: { sticker: "🌀", name: "Portal del Tiempo" }
  },

  // ================= SEMANA 4: CAMPEONES KIDGENIUS Y GRAN FINAL =================
  {
    day: 22,
    week: 4,
    title: "La Cima de la Montaña",
    icon: "🏔️",
    story: "Estamos a 60 metros y subimos 35 metros más hasta la cumbre. ¿A qué altura llegamos?",
    type: "options",
    question: "60 + 35 = ?",
    visuals: ["🏔️ 60 m", "➕", "🧗 35 m"],
    options: ["85 m", "90 m", "95 m", "100 m"],
    correct: "95 m",
    hint: "60 + 30 = 90, y 90 + 5 = ...",
    reward: { sticker: "🏔️", name: "Pico Nevado" }
  },
  {
    day: 23,
    week: 4,
    title: "Reparto de Galletas Dino",
    icon: "🍪",
    story: "Hay 12 galletas de dinosaurio y queremos repartirlas en partes iguales entre 3 amigos. ¿Cuántas le tocan a cada uno?",
    type: "options",
    question: "12 ÷ 3 = ?",
    visuals: ["🍪🍪🍪🍪", "🍪🍪🍪🍪", "🍪🍪🍪🍪"],
    options: ["3", "4", "5", "6"],
    correct: "4",
    hint: "¿Qué número multiplicado por 3 da 12? (3 x 4 = 12).",
    reward: { sticker: "🍪", name: "Mega Galleta" }
  },
  {
    day: 24,
    week: 4,
    title: "El Truco del 9",
    icon: "🪄",
    story: "Geni te enseña un truco: para sumar 9, suma 10 y resta 1. ¿Cuánto es 34 + 9?",
    type: "options",
    question: "34 + 9 = ?",
    visuals: ["34 + 10 = 44", "➡️", "44 - 1 = ❓"],
    options: ["41", "42", "43", "45"],
    correct: "43",
    hint: "34 + 10 = 44, luego 44 - 1 = 43.",
    reward: { sticker: "🪄", name: "Varita de Cristal" }
  },
  {
    day: 25,
    week: 4,
    title: "La Cesta de Gemas",
    icon: "💎",
    story: "Si compras 2 gemas por $15 cada una, ¿cuánto pagas en total?",
    type: "options",
    question: "15 + 15 (o 2 x 15) = ?",
    visuals: ["💎 $15", "➕", "💎 $15"],
    options: ["25", "30", "35", "40"],
    correct: "30",
    hint: "10 + 10 = 20, y 5 + 5 = 10. 20 + 10 = 30.",
    reward: { sticker: "💠", name: "Diamante Legendario" }
  },
  {
    day: 26,
    week: 4,
    title: "El Guardián del Tiempo",
    icon: "⏳",
    story: "¿Cuántos minutos hay en 1 hora y media (1h 30min)?",
    type: "options",
    question: "60 minutos + 30 minutos = ?",
    visuals: ["⏱️ 1 hora = 60 min", "➕", "⏱️ media hora = 30 min"],
    options: ["75 min", "80 min", "90 min", "100 min"],
    correct: "90 min",
    hint: "60 + 30 = 90 minutos.",
    reward: { sticker: "⏳", name: "Reloj de Arena Mágico" }
  },
  {
    day: 27,
    week: 4,
    title: "La Secuencia Prohibida",
    icon: "🧩",
    story: "¿Qué número falta en esta serie multiplicativa: 3, 6, 9, 12, ❓, 18?",
    type: "options",
    question: "3, 6, 9, 12, ❓, 18",
    visuals: ["3️⃣", "6️⃣", "9️⃣", "1️⃣2️⃣", "❓", "1️⃣8️⃣"],
    options: ["13", "14", "15", "16"],
    correct: "15",
    hint: "La tabla del 3: 3 x 5 = ...",
    reward: { sticker: "🧩", name: "Pieza del Enigma" }
  },
  {
    day: 28,
    week: 4,
    title: "La Balanza en Equilibrio",
    icon: "⚖️",
    story: "En el lado izquierdo hay 50 kg. En el derecho hay 30 kg y una piedra misteriosa. ¿Cuánto pesa la piedra?",
    type: "options",
    question: "30 + ❓ = 50",
    visuals: ["⚖️ Izq: 50kg", "⚖️ Der: 30kg + ❓"],
    options: ["10 kg", "20 kg", "25 kg", "30 kg"],
    correct: "20 kg",
    hint: "50 - 30 = 20.",
    reward: { sticker: "⚖️", name: "Balanza de Oro" }
  },
  {
    day: 29,
    week: 4,
    title: "Víspera de Graduación",
    icon: "🎓",
    story: "¡Solo falta 1 día! Resuelve este combo mental: (10 x 5) + 5 = ?",
    type: "options",
    question: "(10 x 5) + 5 = ?",
    visuals: ["10 x 5 = 50", "➕ 5 ➡️", "❓"],
    options: ["50", "55", "60", "65"],
    correct: "55",
    hint: "Primero multiplica 10 x 5 = 50, y súmale 5.",
    reward: { sticker: "📜", name: "Pergamino Sagrado" }
  },
  {
    day: 30,
    week: 4,
    title: "🌟 EL GRAN RETO FINAL: MAESTRO KIDGENIUS",
    icon: "🦖",
    story: "¡FELICITACIONES! Llegaste al Día 30. El T-Rex Supremo te desafía: ¿Cuánto es 100 + 150 - 50?",
    type: "options",
    question: "100 + 150 - 50 = ?",
    visuals: ["🦖👑", "100 + 150 = 250", "250 - 50 = ❓"],
    options: ["150", "200", "250", "300"],
    correct: "200",
    hint: "100 + 150 = 250, y si le restas 50 te quedan 2 centenas exactas.",
    reward: { sticker: "🏆", name: "Copa Dorada KidGenius Supremo" }
  }
];

window.MISSIONS_DATA = MISSIONS_DATA;
